webtalk_init -webtalk_dir /home/chrispy/workspace/FPRock_CmodA735t/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-03-22 00:10:48" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "uck575t5m6tr9ju0pdt5vsaauo" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_46" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "46" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3800X 8-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3093.441 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.593 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1616358472000" -context "vitis\\\\application/1616358472000"
webtalk_add_data -client vitis -key project_type -value "sdk" -context "vitis\\\\application/1616358472000"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\application/1616358472000"
webtalk_add_data -client vitis -key processor -value "microblaze_0" -context "vitis\\\\application/1616358472000"
webtalk_add_data -client vitis -key runtime -value "C/C++" -context "vitis\\\\application/1616358472000"
webtalk_add_data -client vitis -key template -value "sdk" -context "vitis\\\\application/1616358472000"
webtalk_add_data -client vitis -key platform -value "custom" -context "vitis\\\\application/1616358472000"
webtalk_add_data -client vitis -key platform_type -value "fixed" -context "vitis\\\\application/1616358472000"
webtalk_add_data -client vitis -key application_type -value "application" -context "vitis\\\\application/1616358472000"
webtalk_add_data -client vitis -key platform_source -value "platform" -context "vitis\\\\application/1616358472000"
webtalk_add_data -client vitis -key device_family -value "artix7" -context "vitis\\\\application/1616358472000"
webtalk_add_data -client vitis -key fpga -value "xc7a35t" -context "vitis\\\\application/1616358472000"
webtalk_add_data -client vitis -key uid -value "NA" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key RecordType -value "ToolUsage" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key BOOTGEN_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key FLASH_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key MOVE_APP_TO_SYSTEM_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key SDX_EXPORT_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key SDX_IMPORT_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key SDX_BUILD_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key SDX_NO_OP_BUILD_count -value "2" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key TCF_APP_DEBUG_count -value "63" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key TCF_SYSTEM_DEBUG_count -value "15" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key GDB_DEBUG_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key QEMU_DEBUG_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key ESTIMATION_DEBUG_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key SDSOC_TRACE_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key PERFORMANCE_ANALYSIS_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key SPM_ANALYSIS_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key CROSS_TRIGGER_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key TCF_PROFILER_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key APPLICATION_PLATFORM_CHANGE_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key APPLICATION_SYS_CONFIG_CHANGE_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_add_data -client vitis -key SYSTEM_PLATFORM_CHANGE_count -value "0" -context "vitis\\\\tool/1616386248209"
webtalk_transmit -clientid 3864637070 -regid "" -xml /home/chrispy/workspace/FPRock_CmodA735t/webtalk/usage_statistics_ext_vitis.xml -html /home/chrispy/workspace/FPRock_CmodA735t/webtalk/usage_statistics_ext_vitis.html -wdm /home/chrispy/workspace/FPRock_CmodA735t/webtalk/vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
